name: shop
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_slidable: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true  # This ensures the Material Icons font is included

  assets:
    - assets/icons/
    - assets/icons/1.svg
    - assets/images/


  # Optional: Add custom fonts if required
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Bold.ttf


  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
